### ISSUE TITLE
release 2.4.0

### ISSUE THREAD

**Issue by kenglxn** [kenglxn/QRGen#94]
# TODO:
- [ ] remove or implement any unimplemented classes/methods
- [x] generate release log
- [ ] consider cleanup code formatting etc.
- [x] publish artifact
- [x] update readme
  - [x] versions
  - [ ] more explicit description on schema usage. more examples.

**Comment by atomfrede** [comment]
Regarding code formaating I found https://github.com/diffplug/spotless quite useful (currently only supports gradle but maybe thats no problem). Furthermore I was thinking about adding SVG support again via apache batik, which is apache 2 licensed so it won't conflict with qrgens license. What do you think?

**Comment by kenglxn** [comment]
> Regarding code formaating I found https://github.com/diffplug/spotless quite useful (currently only supports gradle but maybe thats no problem)

Nice! Will have a look at it in the holidays.

>  Furthermore I was thinking about adding SVG support again via apache batik, which is apache 2 licensed so it won't conflict with qrgens license. What do you think?

Sounds great. :)

**Comment by atomfrede** [comment]
I will open an issue for the svg support to keep track about it.

**Comment by atomfrede** [comment]
We should also think of at least automatic module naming with regards to java 9 modules: http://branchandbound.net/blog/java/2017/12/automatic-module-name/?utm_content=buffer704a9&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

**Comment by kenglxn** [comment]
indeed. I will have to look into it when I have some more spare time.

**Comment by kenglxn** [comment]
Published 2.4.0 althoug did not get to all the points in this issue. Moving them out to another post release issue, as I don't think the release needs to wait for them https://github.com/kenglxn/QRGen/releases/tag/2.4.0
