### ISSUE TITLE
post 2.4.0 refactorings

### ISSUE THREAD

**Issue by kenglxn** [kenglxn/QRGen#96]
# TODO:
- [ ] remove or implement any unimplemented classes/methods
- [ ] consider cleanup code formatting etc.
- [ ] more explicit description on schema usage. more examples.

see https://github.com/kenglxn/QRGen/issues/94 for discussions on code formatting and java 9 modules.

**Comment by nixbpe** [comment]
Can i help you for this ?

**Comment by kenglxn** [comment]
i always welcome PRs. This issue is not very well defined, but the most important part is more documentation with examples of how to use schema. What schemas are available and how to use them, perhaps even how to extend and define your own schemas.
